server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jean827/AIG.git
          search-paths: 'Projects/MYP/backend/config-service/src/main/resources/configs'
          default-label: main
          timeout: 5
          force-pull: true
  datasource:
    url: jdbc:mysql://localhost:3306/config_service?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: super
    password: 1qazxsw2
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
          # 配置从仓库
          repos:
            secondary:
              pattern: '*/secondary'
              uri: https://github.com/Jean827/AIG.git
              search-paths: 'Projects/MYP/backend/config-service/src/main/resources/configs/secondary'
              default-label: main

# 配置Eureka客户端
# 配置中心需要注册到Eureka，以便其他服务能够发现
# 注意：需要在bootstrap.yml中配置Eureka的地址，避免循环依赖

# 健康检查配置
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# 日志配置
logging:
  level:
    root: INFO
    org.springframework.cloud.config: DEBUG