server:
  port: 5103

spring:
  main:
    allow-circular-references: true
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth_service?useSSL=false&serverTimezone=UTC
    username: super
    password: 1qazxsw2
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  config:
    import: optional:configserver:http://localhost:5100
  # 邮件服务器配置
  mail:
    host: smtp.muyacorp.com
    port: 25
    username: system@muyacorp.com
    password: OGajbH1OhoteFiR8
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
        debug: true  # 启用邮件调试日志

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5101/eureka/
  instance:
    preferIpAddress: true

# JWT配置
app:
  jwtSecret: your-secret-key
  jwtExpirationMs: 86400000
  refreshTokenExpirationMs: 604800000
  frontend.url: http://localhost:5000