server:
  port: 8090

spring:
  main:
    allow-circular-references: true
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth_service?useSSL=false&serverTimezone=UTC
    username: super
    password: 1qazxsw2
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

# JWT配置
app:
  jwtSecret: your-secret-key
  jwtExpirationMs: 86400000
  refreshTokenExpirationMs: 604800000