server:
  port: 8761

spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:http://localhost:8888

# Eureka服务器配置
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 5000