server:
  port: 5101

spring:
  application:
    name: eureka-server

# Eureka配置
server1:
eureka:
  instance:
    hostname: eureka-server1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server2:5102/eureka/
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 5000