server:
  port: 5102

spring:
  application:
    name: eureka-server

# Eureka配置
server2:
eureka:
  instance:
    hostname: eureka-server2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server1:5101/eureka/
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 5000