server:
  port: 5104

spring:
  application:
    name: tenant-service
  datasource:
    url: jdbc:mysql://localhost:3306/tenant_service?useSSL=false&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  config:
    import: optional:configserver:http://localhost:5100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5101/eureka/
  instance:
    preferIpAddress: true

# 租户配置
tenant:
  validation:
    enabled: true
  cache:
    ttl: 3600